name: Android CI

env:
  main_project_module: app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'gradle'

      # 3. Grant gradlew permissions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Create local.properties with SDK path
      - name: Create local.properties
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

      # 5. Build APK Debug ARM64
      - name: Build APK Debug ARM64
        run: ./gradlew assembleDebug -PabiFilter=arm64-v8a --warning-mode all

      # 6. Find and set APK path
      - name: Find Debug ARM64 APK
        run: echo "APK_PATH=$(find ${{ env.main_project_module }}/build/outputs/apk/debug/ -type f -name '*arm64*.apk')" >> $GITHUB_ENV

      # 7. Upload APK artifact
      - name: Upload APK Debug ARM64
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-debug-arm64
          path: ${{ env.APK_PATH }}
